require: rubocop-rails
AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Rails/FilePath:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false
